### ISSUE TITLE
Feedback for Modal Window

### ISSUE THREAD

**Issue by KBeltz** [KBeltz/07-08-js-mini#1]
http://gunner-rhinoceros-67001.bitballoon.com/

**Comment by sumeetjain** [comment]
- [x] Set event listeners in Javascript, not inline HTML.
- [x] Clicking the modal's 'close' button actually does more than you're intending. It actually refreshes the page entirely. That's because of the link's default action, which is to create a new request. One way to solve this is to set `href="#"`.

**Comment by KBeltz** [comment]
@sumeetjain I had the `href="#"` initially, but I couldn't get the main div to show back up when I clicked the close link. I will see what I can figure out.
